import type { Skill } from "@/types";

export const skills: Skill[] = [
  {
    id: "nextjs",
    name: "Next.js",
    category: "Frontend",
    level: 98,
    years: 5,
    projects: 32,
    description: "App Router, RSC, Server Actions, edge middleware, and performance architecture.",
    color: "#ffffff",
  },
  {
    id: "react",
    name: "React",
    category: "Frontend",
    level: 97,
    years: 6,
    projects: 40,
    description: "Advanced patterns, concurrent features, and accessible interface systems.",
    color: "#61dafb",
  },
  {
    id: "typescript",
    name: "TypeScript",
    category: "Languages",
    level: 96,
    years: 5,
    projects: 38,
    description: "Strict typing, domain modeling, and safe API contracts across the stack.",
    color: "#3178c6",
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    category: "Frontend",
    level: 95,
    years: 4,
    projects: 30,
    description: "Design-token driven UI systems with pixel-precise responsive craft.",
    color: "#38bdf8",
  },
  {
    id: "framer",
    name: "Framer Motion",
    category: "Frontend",
    level: 92,
    years: 4,
    projects: 22,
    description: "Orchestrated motion, scroll storytelling, and micro-interactions.",
    color: "#ff4ecd",
  },
  {
    id: "nodejs",
    name: "Node.js",
    category: "Backend",
    level: 90,
    years: 5,
    projects: 28,
    description: "API design, background jobs, and resilient service boundaries.",
    color: "#68a063",
  },
  {
    id: "postgresql",
    name: "PostgreSQL",
    category: "Database",
    level: 88,
    years: 4,
    projects: 20,
    description: "Schema design, indexing strategy, and transactional integrity.",
    color: "#336791",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "Database",
    level: 90,
    years: 3,
    projects: 18,
    description: "Auth, realtime, storage, and vector search for modern apps.",
    color: "#3ecf8e",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "Cloud",
    level: 94,
    years: 4,
    projects: 35,
    description: "Edge deployments, preview workflows, and observability.",
    color: "#ffffff",
  },
  {
    id: "openai",
    name: "OpenAI / AI SDK",
    category: "AI",
    level: 87,
    years: 2,
    projects: 12,
    description: "Streaming agents, RAG systems, and productized AI UX.",
    color: "#10a37f",
  },
  {
    id: "docker",
    name: "Docker",
    category: "DevOps",
    level: 82,
    years: 3,
    projects: 15,
    description: "Containerized services and reproducible local environments.",
    color: "#2496ed",
  },
  {
    id: "git",
    name: "Git / GitHub",
    category: "Tools",
    level: 95,
    years: 7,
    projects: 50,
    description: "Branching strategies, reviews, CI workflows, and open source.",
    color: "#f05032",
  },
  {
    id: "zod",
    name: "Zod",
    category: "Tools",
    level: 93,
    years: 3,
    projects: 25,
    description: "Runtime validation shared between client, server, and APIs.",
    color: "#3068b7",
  },
  {
    id: "gsap",
    name: "GSAP",
    category: "Frontend",
    level: 80,
    years: 2,
    projects: 8,
    description: "Cinematic timelines and scroll-triggered sequences where motion earns its place.",
    color: "#88ce02",
  },
  {
    id: "python",
    name: "Python",
    category: "Languages",
    level: 78,
    years: 3,
    projects: 10,
    description: "Scripting, automation, and light data/AI tooling.",
    color: "#3776ab",
  },
  {
    id: "aws",
    name: "AWS",
    category: "Cloud",
    level: 75,
    years: 3,
    projects: 9,
    description: "S3, Lambda, CloudFront, and pragmatic cloud architecture.",
    color: "#ff9900",
  },
];

export const skillCategories = [
  "Frontend",
  "Backend",
  "Database",
  "Cloud",
  "AI",
  "DevOps",
  "Tools",
  "Languages",
] as const;

export function getSkillsByCategory(category: Skill["category"]) {
  return skills.filter((skill) => skill.category === category);
}
